### ISSUE TITLE
Could you provide script for making b_marmoset infant template?

### ISSUE THREAD

**Issue by John1231983** [jlohmeier/atlasBREX#1]
Hi, Could you provide script for making b_marmoset infant template? Do you use Ants to do it? Thanks

**Comment by jlohmeier** [comment]
You may use ABSORB (https://www.nitrc.org/projects/absorb).

**Comment by John1231983** [comment]
@jlohmeier : So complex to install. Have you try the ants to make it?

**Comment by jlohmeier** [comment]
Actually, ABSORB is quite user friendly (offers GUI/command line + detailed manual + supports multiple platforms)! For support and questions regarding ABSORB, please contact jiahj@med.unc.edu.
Of course, other template building solutions (such as available in ANTs) should work as well.
