### ISSUE TITLE
Cannot modify `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS`

### ISSUE THREAD

**Issue by lamyj** [jlohmeier/atlasBREX#2]
When using the ANTs pipeline, the number of threads is set to an arbitrary value of 32. It should be possible to let the user define it, with a sane default based. The following snippet checks if the variable is defined, and it not, sets it to the number of CPUs (if `nproc` is available, otherwise to 1).

```bash
#Number of threads for ANTs
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=${ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS:-$(nproc 2>/dev/null || echo 1)}
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS
```

**Comment by jlohmeier** [comment]
Thank you for the suggestion - now implemented!
