### ISSUE TITLE
error atlasBREX  line 489: declare: -A: invalid option

### ISSUE THREAD

**Issue by Alex-mri** [jlohmeier/atlasBREX#4]
Hi, 

I wanted to try atlasBREX to skull stripped Dog brains on MacOs Catalina, although I have very quickly an error message. I have fsl v6.0.1 and ANTs installed. 

I use in terminal: 
bash atlasBREX.sh -b invivoTemplate.nii.gz -nb invivoTemplate-onlySkull.nii.gz -h T1_raw.nii.gz -f 0.2

and I have the error message:
atlasBREX.sh: line 489: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

Can you help me resolve the issue?

Thanks

**Comment by jlohmeier** [comment]
Please check your bash version: bash --version

You probably use an older bash version <4.
Either change the respective line (489) in the code or update bash.
